### ISSUE TITLE
optional 5. Signatur für 2015er Images

### ISSUE THREAD

**Issue by mmalte** [ffac/manifest#20]
Falls doch wieder ein Image mit Firmware v2015.1.2.s.06 oder älter auftauchen sollte, bräuchte es ein weitere signatur:

https://github.com/ffac/site/blob/v2015.1.2.s.06/site.conf

**Comment by flammy** [comment]
**redundant signature in [from-2019.1.x ](https://github.com/ffac/manifest/tree/from-2019.1.x)**
- [x] e7641388008e30055f2f61a12a12b4a4aae9ae2d

**necessary signature in [legacy ](https://github.com/ffac/manifest/tree/legacy)**
- [x] 60717ebbc2b2b2b32f42259dff15a72de6c80e44
- [x] bf83d3e779ccf7ba3977201b49f1d7dc9f94ffa3
- [x] 8eee3293d0ac9f3d0ee28154cb1b014b0b40d95d

**Comment by mmalte** [comment]
Solved by 60717ebbc2b2b2b32f42259dff15a72de6c80e44
