### ISSUE TITLE
autoupdate von 2019.1-1-s auf 2019.1.2-2-s

### ISSUE THREAD

**Issue by mmalte** [ffac/manifest#31]
Diese Komni ist bei kaum einem Entwickler, aber bei fast allen Knoten die das Autoupdate im Feld Betrifft der Fall.

Nach Möglichkeit ein Knoten der nicht per Downgrade auf die 2019.1-1-s gebracht wurde.

**Comment by jannic** [comment]
ffac-jannic-test11 (TP-Link Archer C7 v2) und ffac-schloss-rahe-strasse (TP-Link TL-WR841N/ND v9) wurden per Autoupdater von 2019.1-1-stable auf 2019.1.2-2-stable updatet. Kein vorheriges Downgrade.

**Comment by mmalte** [comment]
zusätzlich auf khg-uplink einem FUTRO S550 direkt von 2019.1-1 durchgeführt
